### ISSUE TITLE
Add the ability to change shortcuts

### ISSUE THREAD

**Issue by opensas** [redmunds/brackets-display-shortcuts#27]
It would be great if you could add the funcionality of this plugin: https://bitbucket.org/sacah/brackets-key-remapper

The author is even asking for help,  think you could join forces and make a single plugin

**Comment by redmunds** [comment]
@opensas, [sacah](https://bitbucket.org/sacah) I added Override Shortcut and Disable Shortcut commands in [this pull request](https://github.com/redmunds/brackets-display-shortcuts/pull/45). Let me know how it works for you. Closing this request.
