### ISSUE TITLE
[Bug] Shortcut OSX doesnt work

### ISSUE THREAD

**Issue by schroef** [redmunds/brackets-display-shortcuts#55]
bracket 1.13
osx 10.11.6

I tried the control + alt + / shortcut on ac but nothing happens. It simply adds an forward slash then.

**Comment by schroef** [comment]
Sorry had done proper research. It seems it wasnt enabled. But by doing so i see errors about a missing text file

It looks like the lib folder is missing. ill try to download and install it again from this gitHub and do a manual install. Hope this fixes this.

Errors in the dev tool
<img width="1180" alt="screen shot 2018-10-07 at 20 24 19" src="https://user-images.githubusercontent.com/6923008/46588767-3853d980-ca6f-11e8-97b0-6b0170181bf6.png">

Content bracket display shortcut folder
<img width="652" alt="screen shot 2018-10-07 at 20 26 09" src="https://user-images.githubusercontent.com/6923008/46588772-4b66a980-ca6f-11e8-8ff1-7567a8937547.png">

EDIT
seem the version online here also is missing this folder

**Comment by schroef** [comment]
When i deleted it and did a reinstall using plugin/addon manager. I get this error

Again i see that missing folder and file. Im not sure where this comes from, because it doesnt seem to be in your code. When i did a search for these files or text in the code, its not there. Do these need to be created by Brackets orso?

**Comment by schroef** [comment]
IM wild guessing here, in other plugins i see they call or import the module 'mustache'. In this plugin i dont see it get imported i think?

I dont know much about this code or language. I know a bit of Python and some other.

**Comment by schroef** [comment]
Okay that was the fix :)

i added this line below CodeMirror import in main.js:33

`brk.Mustache = brackets.getModule("thirdparty/mustache/mustache");`

Now it works again :)
<img width="1090" alt="screen shot 2018-10-07 at 20 43 50" src="https://user-images.githubusercontent.com/6923008/46588927-ce88ff00-ca71-11e8-9c17-f5ca366fd2fd.png">

**Comment by redmunds** [comment]
Thanks. Do you want to submit a pull request?

**Comment by redmunds** [comment]
This is now fixed. Thanks for filing bugs. Thanks even more for telling me what the fix was :)

**Comment by schroef** [comment]
hahah that was easy fix right ;)

I guess not much people use this or they are Windows users. This bug probably has ben here for a long while.

PS for what can i use the action "Copy to document"?
I went looking for this add because i wanted to add shortcuts to the splitview and vertical/horizontal splitview. It took me quite long to actually figure out that they can easily be added in the settings files. This part isnt really proper documented i must say. 

THere is also writing about the function "Copy to document". But what i dont understand is the usage for this, the formatting cant be used in Brackets itself, atleast not in setttings files.

**Comment by redmunds** [comment]
> for what can i use the action "Copy to document"?

I added that to make it easy to create documentation in HTML format with all the info of all of the shortcuts. Try this:

1. File > New to create a new file
1. Click "Copy to Current Document"

At that point, you can edit, copy, and paste as needed.

> It took me quite long to actually figure out that they can easily be added in the settings files. This part isn't really proper documented i must say.

It's not documented directly, but if you right-click on any row and click "Override Shortcut for Command", it opens the keymap.json file, and even creates an entry with the Command name for you.

**Comment by schroef** [comment]
I find that keymap.json file weird. Im not sure what im doing wrong. But it keeps saying its not a proper json file.

Ive once set it but when i add something i keep getting the error. I now erased all data and copy pasted the base from the page and still keeps bugging. I looked at [this page](https://github.com/adobe/brackets/wiki/User-Key-Bindings)

```
{
    "overrides": {
        "<key>": "<command-id>"
        [, "<key>": "<command-id>"]
    }
}
```

PS did you change the shortcut for show shortcuts? now its cmd+shift+~ on OSX

**Comment by schroef** [comment]
Weird thing is the shortcut doesnt do anything now? Not sure what happened there. I thought that it was change to Shift+cmd+~ but that is Toggle Panels. Though it does show then, ctrl+alt+/ doesnt do anything now.

I do see this in the dev tools. Seems like it still wants to add cmd+shft+/

PS i tried adding =="darwin" instead of mac, but didnt seem to help

<img width="856" alt="screen shot 2018-10-08 at 23 34 27" src="https://user-images.githubusercontent.com/6923008/46645404-ca80de00-cb52-11e8-9bc6-283b5226f767.png">

**Comment by schroef** [comment]
Okay this one will work on mac `Alt-Cmd-``
