### ISSUE TITLE
main.js:165 Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by svArtist** [redmunds/brackets-display-shortcuts#57]
Upon clicking "Show Shortcuts", the error 
> main.js:165 Uncaught TypeError: Cannot read property 'on' of undefined

is thrown and the panel stays empty.
It looks like some IDs can end up pointing to commands which don't exist (anymore).

**Comment by redmunds** [comment]
Fixed by PR #58

**Comment by redmunds** [comment]
@svArtist Thanks for fix. I uploaded v1.4.1 to Brackets Extension Registry, so you should now see it in Extension Manager.
